@startuml
class DataListController {
    + DataListController(mediator:IMediator)
    + <<async>> GetDataListFromIdAsync(id:string) : Task<IActionResult>
    + <<async>> AddKeyValuePair(value:DataListModel) : Task<IActionResult>
    + <<async>> UpdateKeyValuePair(value:SingleDataModel) : Task<IActionResult>
    + <<async>> DeleteKeyValuePairAsync(id:string) : Task<IActionResult>
}
ControllerBase <|-- DataListController
@enduml
