@startuml
class ApplicationConfigurationExtension <<static>> {
    + {static} SetUpApiDocumentation(services:IServiceCollection) : IServiceCollection
    + {static} SetUpExcepions(app:IApplicationBuilder) : IApplicationBuilder
}
@enduml
