@startuml
class ConcurrentDictionaryService <<sealed>> {
    + ConcurrentDictionaryService()
    + CreateAsync(key:string, list:List<object>) : Task
    + AppendAsync(key:string, value:object) : Task
    + GetAsync(key:string) : Task<List<object>>
    + DeleteAsync(id:string) : Task<List<object>>
}
IConcurrentDictionaryService <|-- ConcurrentDictionaryService
@enduml
