@startuml
!include .\\ElegantWebApi\Program.puml
!include .\\ElegantWebApi\WeatherForecast.puml
!include .\\ElegantWebApi\Controllers\DataListController.puml
!include .\\ElegantWebApi\Controllers\WeatherForecastController.puml
!include .\\ElegantWebApi\DTOs\MyDataList.puml
!include .\\ElegantWebApi\Exceptions\ValidErrorCode.puml
!include .\\ElegantWebApi\Extensions\ApplicationConfigurationExtension.puml
!include .\\ElegantWebApi\Extensions\ServiceCollectionExtensions.puml
!include .\\ElegantWebApiDomain\Entities\DataListModel.puml
!include .\\ElegantWebApiDomain\Entities\SingleDataModel.puml
!include .\\ElegantWebApiInfrastructure\Contracts\IConcurrentDictionaryService.puml
!include .\\ElegantWebApiInfrastructure\Contracts\IExpirationDataService.puml
!include .\\ElegantWebApiInfrastructure\Services\ConcurrentDictionaryHostedService.puml
!include .\\ElegantWebApiInfrastructure\Services\ConcurrentDictionaryService.puml
!include .\\ElegantWebApiInfrastructure\Services\ExpirationDataService.puml
!include .\\ElegantWebApiAppication\Features\AddDataList\AddDataListCommand.puml
!include .\\ElegantWebApiAppication\Features\AddDataList\AddDataListCommandValidator.puml
!include .\\ElegantWebApiAppication\Features\AddDataList\AddDataListHandler.puml
!include .\\ElegantWebApiAppication\Features\AppendValue\AppendValueCommand.puml
!include .\\ElegantWebApiAppication\Features\AppendValue\AppendValueCommandValidator.puml
!include .\\ElegantWebApiAppication\Features\AppendValue\AppendValueHandler.puml
!include .\\ElegantWebApiAppication\Features\DeleteDataList\DeleteRecordCommandValidator.puml
!include .\\ElegantWebApiAppication\Features\DeleteDataList\DeleteRecordListCommand.puml
!include .\\ElegantWebApiAppication\Features\DeleteDataList\DeleteRecordListHandler.puml
!include .\\ElegantWebApiAppication\Features\GetDataList\GetDataListCommand.puml
!include .\\ElegantWebApiAppication\Features\GetDataList\GetDataListHandler.puml
!include .\\ElegantWebApi\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.Api.AssemblyInfo.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.Api.GlobalUsings.g.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.Api.MvcApplicationPartsAssemblyInfo.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.AssemblyInfo.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.Core.AssemblyInfo.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.Core.GlobalUsings.g.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.Core.MvcApplicationPartsAssemblyInfo.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.GlobalUsings.g.puml
!include .\\ElegantWebApi\obj\Debug\net80\ElegantWebApi.MvcApplicationPartsAssemblyInfo.puml
!include .\\ElegantWebApiAppication\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\ElegantWebApiAppication\obj\Debug\net80\ElegantWebApi.Appication.AssemblyInfo.puml
!include .\\ElegantWebApiAppication\obj\Debug\net80\ElegantWebApi.Appication.GlobalUsings.g.puml
!include .\\ElegantWebApiAppication\obj\Debug\net80\ElegantWebApi.Application.AssemblyInfo.puml
!include .\\ElegantWebApiAppication\obj\Debug\net80\ElegantWebApi.Application.GlobalUsings.g.puml
!include .\\ElegantWebApiDomain\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\ElegantWebApiDomain\obj\Debug\net80\ElegantWebApi.Domain.AssemblyInfo.puml
!include .\\ElegantWebApiDomain\obj\Debug\net80\ElegantWebApi.Domain.GlobalUsings.g.puml
!include .\\ElegantWebApiInfrastructure\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\ElegantWebApiInfrastructure\obj\Debug\net80\ElegantWebApi.Infrastructure.AssemblyInfo.puml
!include .\\ElegantWebApiInfrastructure\obj\Debug\net80\ElegantWebApi.Infrastructure.GlobalUsings.g.puml
@enduml
